version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: kwbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env.example
    ports:
      - '3001:3001'
    depends_on:
      - db
      - redis
      - python-nlp
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: node dist/worker/worker.js
    env_file:
      - backend/.env.example
    depends_on:
      - redis
      - db
      - python-nlp
  python-nlp:
    build:
      context: ./python-nlp
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
volumes:
  db-data: {}
