# KWBank Full Stack Docker Compose
# This file starts all services needed for local development

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: kwbank-postgres
    environment:
      POSTGRES_USER: kwbank
      POSTGRES_PASSWORD: kwbank
      POSTGRES_DB: kwbank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kwbank"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kwbank-network

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: kwbank-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kwbank-network

  # Python NLP Microservice
  python-nlp:
    build:
      context: ./python-nlp
      dockerfile: Dockerfile
    container_name: kwbank-python-nlp
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - kwbank-network

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kwbank-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=kwbank
      - DB_PASSWORD=kwbank
      - DB_NAME=kwbank
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      python-nlp:
        condition: service_started
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - kwbank-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kwbank-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - kwbank-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  kwbank-network:
    driver: bridge
